"""
health_passport.py — builds a single self-contained HTML health passport:
profile, conditions, allergies, medications, emergency data, recent
vitals, risk factors and trend charts (inline SVG). Meant to be printed
or shown to a doctor. Personal data never leaves the machine.
"""
from __future__ import annotations

import os
import tempfile
from datetime import datetime
from typing import Any

from i18n import is_fa


def _esc(s: Any) -> str:
    return str(s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def passport_data() -> dict[str, Any]:
    from emergency_card import card_data
    from patient_profile import load_profile
    from health_vitals import history
    p = load_profile()
    ice = card_data()
    try:
        from health_vitals import bmi as _bmi_unused
    except Exception:
        pass
    bmi_val = None
    try:
        w = float(p.get("weight_kg") or 0)
        h = float(p.get("height_cm") or 0) / 100.0
        if w > 0 and h > 0:
            bmi_val = round(w / (h * h), 1)
    except (TypeError, ValueError):
        bmi_val = None
    return {"profile": p, "ice": ice, "vitals": history(10), "bmi": bmi_val}


def build_html(lang: str | None = None) -> str:
    fa = (lang == "fa") if lang else is_fa()
    d = passport_data()
    p, ice, vit = d["profile"], d["ice"], d["vitals"]
    if fa:
        title = "پاسپورت سلامت"
        labels = [("نام", "Name"), ("سن", "Age"), ("جنسیت", "Sex"), ("قد/وزن", "Height/Weight"),
                  ("BMI", "BMI"), ("گروه خونی", "Blood type"), ("بیماری‌ها", "Conditions"),
                  ("حساسیت‌ها", "Allergies"), ("داروها", "Medications"), ("تماس اضطراری", "Emergency contact")]
        vit_head = ["تاریخ", "فشار", "ضربان", "قند", "وزن", "اکسیژن"]
        empty = "ثبت نشده"
        sect_vitals = "علائم حیاتی اخیر"
        sect_charts = "نمودار روند"
        foot = ("تولیدشده توسط NexusMed 2077 — اطلاعات شخصی است و فقط برای مراقبت درمانی. "
                "این سند جایگزین پرونده‌ی رسمی پزشک نیست.")
    else:
        title = "Health Passport"
        labels = [("Name", "نام"), ("Age", "سن"), ("Sex", "جنسیت"), ("Height/Weight", "قد/وزن"),
                  ("BMI", "BMI"), ("Blood type", "گروه خونی"), ("Conditions", "بیماری‌ها"),
                  ("Allergies", "حساسیت‌ها"), ("Medications", "داروها"), ("Emergency contact", "تماس اضطراری")]
        vit_head = ["Date", "BP", "Heart rate", "Glucose", "Weight", "SpO2"]
        empty = "not recorded"
        sect_vitals = "Recent vitals"
        sect_charts = "Trend charts"
        foot = ("Generated by NexusMed 2077 - personal data for medical care only. "
                "This document does not replace an official medical record.")
    hw = f"{p.get('height_cm') or '?'} cm / {p.get('weight_kg') or '?'} kg"
    contact = (str(ice.get("contact_name") or "") + " " + str(ice.get("contact_phone") or "")).strip()
    rows = [
        _esc(p.get("name") or empty),
        _esc(p.get("age") or empty),
        _esc(p.get("gender") or empty),
        _esc(hw),
        _esc(d["bmi"] if d["bmi"] else empty),
        _esc(ice.get("blood_type") or empty),
        _esc(", ".join(ice.get("conditions") or []) or empty),
        _esc(", ".join(ice.get("allergies") or []) or empty),
        _esc(", ".join(ice.get("medications") or []) or empty),
        _esc(contact or empty),
    ]
    table = "".join(
        f'<tr><th style="text-align:{"right" if fa else "left"};padding:5px 10px;border-bottom:1px solid #d8dee9;'
        f'font-size:13px;color:#455770">{_esc(l[0])}</th>'
        f'<td style="padding:5px 10px;border-bottom:1px solid #d8dee9;font-size:14px;font-weight:600">{v}</td></tr>'
        for l, v in zip(labels, rows))
    vit_rows = ""
    for e in vit:
        vit_rows += ("<tr>"
                     + f'<td style="padding:4px 8px;border-bottom:1px solid #e5e9f0">{_esc(str(e.get("ts",""))[:16])}</td>'
                     + f'<td style="padding:4px 8px;border-bottom:1px solid #e5e9f0">{_esc(e.get("systolic_bp","—"))}/{_esc(e.get("diastolic_bp","—"))}</td>'
                     + f'<td style="padding:4px 8px;border-bottom:1px solid #e5e9f0">{_esc(e.get("heart_rate","—"))}</td>'
                     + f'<td style="padding:4px 8px;border-bottom:1px solid #e5e9f0">{_esc(e.get("glucose","—"))}</td>'
                     + f'<td style="padding:4px 8px;border-bottom:1px solid #e5e9f0">{_esc(e.get("weight_kg","—"))}</td>'
                     + f'<td style="padding:4px 8px;border-bottom:1px solid #e5e9f0">{_esc(e.get("spo2","—"))}</td></tr>')
    vit_table = f'<table style="border-collapse:collapse;width:100%;font-size:12px"><tr>' + "".join(
        f'<th style="padding:4px 8px;text-align:{"right" if fa else "left"};color:#455770">{_esc(h)}</th>'
        for h in vit_head) + f'</tr>{vit_rows}</table>' if vit_rows else (
        f'<p style="color:#8a97ab;font-size:12px">{_esc(empty)}</p>')
    charts_svg = ""
    try:
        from vitals_chart import all_charts
        charts_svg = "".join(all_charts(60, fa))
    except Exception:
        charts_svg = ""
    charts_div = (f'<div style="display:grid;gap:10px">{charts_svg}</div>' if charts_svg else
                  f'<p style="color:#8a97ab;font-size:12px">{_esc(empty)}</p>')
    generated = datetime.now().strftime("%Y-%m-%d %H:%M")
    return f"""<!doctype html><html lang="{("fa" if fa else "en")}" dir="{("rtl" if fa else "ltr")}">
<head><meta charset="utf-8"><title>{_esc(title)}</title></head>
<body style="margin:0;font-family:Vazirmatn,Tahoma,Arial,sans-serif;background:#eef1f6">
<div style="max-width:760px;margin:18px auto;background:#fff;border-radius:14px;overflow:hidden;box-shadow:0 4px 22px #0f1b3022">
<div style="background:#0f1b30;color:#fff;padding:16px 20px">
<div style="font-size:21px;font-weight:800">{_esc(title)} — NexusMed 2077</div>
<div style="font-size:11px;color:#9fb2d0;margin-top:4px">{generated}</div></div>
<div style="padding:18px">
<table style="border-collapse:collapse;width:100%">{table}</table>
<h3 style="font-size:15px;margin:20px 0 8px">{_esc(sect_vitals)}</h3>
{vit_table}
<h3 style="font-size:15px;margin:20px 0 8px">{_esc(sect_charts)}</h3>
{charts_div}
</div>
<div style="background:#f2f5fa;color:#5a6b85;padding:10px 20px;font-size:11px">{_esc(foot)}</div>
</div></body></html>"""


def save(path: str | None = None, lang: str | None = None) -> dict[str, Any]:
    fa = (lang == "fa") if lang else is_fa()
    path = path or os.path.join(tempfile.gettempdir(), "nexusmed_health_passport.html")
    try:
        with open(path, "w", encoding="utf-8") as f:
            f.write(build_html(lang))
        return {"ok": True, "path": path,
                "message_fa": ("پاسپورت سلامت ساخته شد — در مرورگر باز می‌شود؛ پرینتش کن یا به پزشک نشان بده."
                               if fa else "Health passport created - opening in the browser; print it or show it to your doctor.")}
    except Exception as e:
        return {"ok": False, "message_fa": str(e)}
